[env]
TERM = "alacritty"
COLORTERM = "truecolor"

[window]
opacity = 0.92
padding = { x = 8, y = 8 }
decorations = "full"

[font]
normal = { family = "IosevkaTermSlab Nerd Font Mono", style = "Regular" }
bold = { family = "IosevkaTermSlab Nerd Font Mono", style = "Bold" }
italic = { family = "IosevkaTermSlab Nerd Font Mono", style = "Italic" }
bold_italic = { family = "IosevkaTermSlab Nerd Font Mono", style = "Bold Italic" }
size = 11.0

[cursor]
style = "Block"
vi_mode_style = "Block"
blink_interval = 0

[bell]
animation = "Linear"

[colors.primary]
background = "#1f1f28"
foreground = "#dcd7ba"

[colors.cursor]
text   = "#1f1f28"
cursor = "#dcd7ba"

[colors.selection]
text       = "#c8c093"
background = "#2d4f67"

[colors.normal]
black   = "#16161d"
red     = "#c34043"
green   = "#76946a"
yellow  = "#c0a36e"
blue    = "#7e9cd8"
magenta = "#957fb8"
cyan    = "#6a9589"
white   = "#c8c093"

[colors.bright]
black   = "#727169"
red     = "#e82424"
green   = "#98bb6c"
yellow  = "#e6c384"
blue    = "#7fb4ca"
magenta = "#938aa9"
cyan    = "#7aa89f"
white   = "#dcd7ba"

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "Return", mods = "Shift", chars = "\u001B\r" },
]
