#!/bin/sh

export PATH="$HOME/.local/bin:$PATH"

if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    exec dbus-run-session "$0" "$@"
fi

export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=dwl
export XDG_SESSION_DESKTOP=dwl

export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM='wayland;xcb'
export SDL_VIDEODRIVER=wayland
export CLUTTER_BACKEND=wayland

exec dwl -s "$HOME/.local/bin/dwl-autostart"
