#!/bin/sh
base="/sys/class/backlight/intel_backlight"
cur="$(cat "$base/brightness" 2>/dev/null)" || { printf "bri?"; exit; }
max="$(cat "$base/max_brightness" 2>/dev/null)" || { printf "bri?"; exit; }
printf "󰃠 %d%%" "$((cur * 100 / max))"
